### ISSUE TITLE
Swedbank DK link dur ik

### ISSUE THREAD

**Issue by eKristensen** [scanpaydk/docs.scanpay.dk#2]
https://docs.scanpay.dk/acquiring-banks

**Comment by eKristensen** [comment]
Gammelt link: https://www.swedbank.dk/card-services/ansog-om-aftale/

Nyt link: https://www.swedbank.dk/erhverv/card-services/ansog-om-aftale/

**Comment by ulrikmoe** [comment]
Det er nu opdateret i mit lokale repository. Tak for feedback 👍
